### ISSUE TITLE
Number of areas drawn sometimes not shown

### ISSUE THREAD

**Issue by wmcclin** [seasketch/next#449] opened 2022-11-14 16:29 UTC
This is an old bug that I thought had been fixed. Sometimes, in the dialog box where you can review the number of shapes you've drawn per sector, instead of a number, it reads "AreaCount_plural".

This one is for a demo survey I've created for students at Scripps (https://next.seasket.ch/scripps/admin/surveys/159)

<img width="1629" alt="Screenshot 2022-11-14 at 8 26 42 AM" src="https://user-images.githubusercontent.com/932832/201713401-f187fcde-f46c-4a71-a58e-58cc9836f6ca.png">

**Comment by underbluewaters** [comment] 2023-01-19 21:04
Duplicate of #312

**Closed by underbluewaters** 2023-01-19 21:04 UTC
Labels: bug
