### ISSUE TITLE
Point shapefiles and flatgeobuffs are treated as polygons.

### ISSUE THREAD

**Issue by wmcclin** [seasketch/next#460] opened 2022-12-16 21:03 UTC
When I upload files with points, they don't display because it appears that the data are treated as polygons, not points. If edit the style like this, it renders:

<img width="1342" alt="Screenshot 2022-12-16 at 1 02 38 PM" src="https://user-images.githubusercontent.com/932832/208188499-c8343630-9d5b-4c3b-9f12-e221454ce557.png">

Would be good if SeaSketch recognized it as a point file.

**Comment by underbluewaters** [comment] 2023-01-09 23:42
Duplicate of #474

**Closed by underbluewaters** 2023-01-09 23:42 UTC
Labels: bug
