### ISSUE TITLE
Report Caching

### ISSUE THREAD

**Issue by wmcclin** [seasketch/next#557] opened 2023-02-04 18:17 UTC
We really need the ability to cache reports, especially for long running analyses. When analyzing large plans with complex data (e.g., the Maldives collection analysis for plans like this one: http://seasket.ch/OM1ooeEkOa), it's not uncommon for plans to take 2 minutes to run. I shouldn't have to do this each time the plan is analyzed if nothing has changed. When it a workshop, having to repeatedly run the analysis after closing the report is time consuming.

**Comment by underbluewaters** [comment] 2023-02-04 20:55
There’s a lot to unpack with report running time right now. I noticed report caching not working well some time after the websocket implementation was deployed. It’s not a clear cut case of caching just not working at all though. We know it works sometimes, since SSN was sending stale cache keys and we got stale results! Those stale results didn’t seem to get delivered all that quick though. 

What I’ve noticed is that some report cards load quickly, as if from cache, and then others like the size report take a very long time. Sometimes it just doesn’t even show up and I need to reopen the report.

**Comment by twelch** [comment] 2023-02-06 06:27
This is a duplicate of https://github.com/seasketch/geoprocessing/issues/102, which I think is the right repo to track this, as it's not I would say an issue on the seasketch platform side.  I'd like to suggest we please move discussion over there.

It's a longstanding issue as Chad noted, and not necessarily simple.  The related code is also not well documented with limited test coverage.

**Closed by twelch** 2023-02-06 06:27 UTC
Labels: enhancement
